version: 2
jobs:
  build:

    working_directory: ~/ohpenpoc

#    docker:
#      - image: circleci/openjdk:8-jdk-browsers
#      - image: circleci/postgres:9.6.3-alpine
#        environment:
#          POSTGRES_USER: root
#          POSTGRES_DB: circle_test

    steps:

      - checkout

      - restore_cache:
          key: ohpenpoc-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: ohpenpoc-{{ checksum "pom.xml" }}

      - run: mvn package

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/poc-1.0-SNAPSHOT.jar